//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageDetect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterlist
    {
        private string iD;

        public string GetID()
        {
            return iD;
        }

        public void SetID(string value)
        {
            iD = value;
        }

        private string tITLE;

        public string GetTITLE()
        {
            return tITLE;
        }

        public void SetTITLE(string value)
        {
            tITLE = value;
        }

        private string aRTIST;

        public string GetARTIST()
        {
            return aRTIST;
        }

        public void SetARTIST(string value)
        {
            aRTIST = value;
        }

        private string aLBUM;

        public string GetALBUM()
        {
            return aLBUM;
        }

        public void SetALBUM(string value)
        {
            aLBUM = value;
        }

        private string lABEL;

        public string GetLABEL()
        {
            return lABEL;
        }

        public void SetLABEL(string value)
        {
            lABEL = value;
        }

        private string iSRC;

        public string GetISRC()
        {
            return iSRC;
        }

        public void SetISRC(string value)
        {
            iSRC = value;
        }

        private string cOMP_ID;

        public string GetCOMP_ID()
        {
            return cOMP_ID;
        }

        public void SetCOMP_ID(string value)
        {
            cOMP_ID = value;
        }

        private string cOMP_TITLE;

        public string GetCOMP_TITLE()
        {
            return cOMP_TITLE;
        }

        public void SetCOMP_TITLE(string value)
        {
            cOMP_TITLE = value;
        }

        private string cOMP_ISWC;

        public string GetCOMP_ISWC()
        {
            return cOMP_ISWC;
        }

        public void SetCOMP_ISWC(string value)
        {
            cOMP_ISWC = value;
        }

        private string cOMP_WRITERS;

        public string GetCOMP_WRITERS()
        {
            return cOMP_WRITERS;
        }

        public void SetCOMP_WRITERS(string value)
        {
            cOMP_WRITERS = value;
        }

        private string cOMP_CUSTOM_ID;

        public string GetCOMP_CUSTOM_ID()
        {
            return cOMP_CUSTOM_ID;
        }

        public void SetCOMP_CUSTOM_ID(string value)
        {
            cOMP_CUSTOM_ID = value;
        }

        private string qUANTILE;

        public string GetQUANTILE()
        {
            return qUANTILE;
        }

        public void SetQUANTILE(string value)
        {
            qUANTILE = value;
        }

        private int indent;

        public int GetIndent()
        {
            return indent;
        }

        public void SetIndent(int value)
        {
            indent = value;
        }

        private byte langVi;

        public byte GetLangVi()
        {
            return langVi;
        }

        public void SetLangVi(byte value)
        {
            langVi = value;
        }
    }
}
